### ISSUE TITLE
Share editor with specific schema loaded.

### ISSUE THREAD

**Issue by TobiasNx** [skohub-io/skohub-editor#84] opened 2021-11-15 10:20 UTC
In context of ORCA the link  https://skohub.io/editor/ is shared with the intention to distribute the schema sample of the ORCA application profil but that obviously not the right link.

There should be an option to share the editor with an loaded schema.

**Comment by acka47** [comment] 2021-11-15 10:28
Duplicate of #5 which is already implemented, see e.g. https://skohub.io/editor/?schema=https://malis21.acka47.net/data/beispielschema.json. Closing.

**Closed by acka47** 2021-11-15 10:28 UTC

**Comment by TobiasNx** [comment] 2021-11-16 08:27
Okay, thats cool. However as a user I do not know this is possible neither the UI nor the URL resemble the link that you shared if you load it in  https://skohub.io/editor

**Comment by TobiasNx** [comment] 2021-11-16 08:32
Also the URL does not change if you load another schema: https://skohub.io/editor/?schema=https://malis21.acka47.net/data/beispielschema.json

Should I open another ticket for UI share link and the URL to be dynamic resembling the loaded schema?
